# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Constraint/MIPS_CPU.xdc

# Block Designs: bd/MIPS_CPU/MIPS_CPU.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPS_CPU || ORIG_REF_NAME==MIPS_CPU}]

# IP: bd/MIPS_CPU/ip/MIPS_CPU_ALU32_0_0/MIPS_CPU_ALU32_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPS_CPU_ALU32_0_0 || ORIG_REF_NAME==MIPS_CPU_ALU32_0_0}]

# IP: bd/MIPS_CPU/ip/MIPS_CPU_CONTROL_UNIT_0_0/MIPS_CPU_CONTROL_UNIT_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPS_CPU_CONTROL_UNIT_0_0 || ORIG_REF_NAME==MIPS_CPU_CONTROL_UNIT_0_0}]

# IP: bd/MIPS_CPU/ip/MIPS_CPU_DATAPATH_0_0/MIPS_CPU_DATAPATH_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPS_CPU_DATAPATH_0_0 || ORIG_REF_NAME==MIPS_CPU_DATAPATH_0_0}]

# IP: bd/MIPS_CPU/ip/MIPS_CPU_DATA_MEM_0_0/MIPS_CPU_DATA_MEM_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPS_CPU_DATA_MEM_0_0 || ORIG_REF_NAME==MIPS_CPU_DATA_MEM_0_0}]

# IP: bd/MIPS_CPU/ip/MIPS_CPU_KEY2INST_0_0/MIPS_CPU_KEY2INST_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPS_CPU_KEY2INST_0_0 || ORIG_REF_NAME==MIPS_CPU_KEY2INST_0_0}]

# IP: bd/MIPS_CPU/ip/MIPS_CPU_REGFILE_0_0/MIPS_CPU_REGFILE_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPS_CPU_REGFILE_0_0 || ORIG_REF_NAME==MIPS_CPU_REGFILE_0_0}]

# IP: bd/MIPS_CPU/ip/MIPS_CPU_SHOW_ON_LED_0_0/MIPS_CPU_SHOW_ON_LED_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPS_CPU_SHOW_ON_LED_0_0 || ORIG_REF_NAME==MIPS_CPU_SHOW_ON_LED_0_0}]

# IP: bd/MIPS_CPU/ip/MIPS_CPU_clk_wiz_0_0/MIPS_CPU_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPS_CPU_clk_wiz_0_0 || ORIG_REF_NAME==MIPS_CPU_clk_wiz_0_0}]

# XDC: bd/MIPS_CPU/ip/MIPS_CPU_clk_wiz_0_0/MIPS_CPU_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MIPS_CPU_clk_wiz_0_0 || ORIG_REF_NAME==MIPS_CPU_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/MIPS_CPU/ip/MIPS_CPU_clk_wiz_0_0/MIPS_CPU_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MIPS_CPU_clk_wiz_0_0 || ORIG_REF_NAME==MIPS_CPU_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/MIPS_CPU/ip/MIPS_CPU_clk_wiz_0_0/MIPS_CPU_clk_wiz_0_0_ooc.xdc

# XDC: bd/MIPS_CPU/MIPS_CPU_ooc.xdc
