# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7a35tcpg236-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir e:/Github/xupsh/Basys3-Git/Projects_2016.2/1_Logic_Design/3_State_Machine/Single_Cycle_32bits_processor/src/prj/MIPS_CPU.cache/wt [current_project]
set_property parent.project_path e:/Github/xupsh/Basys3-Git/Projects_2016.2/1_Logic_Design/3_State_Machine/Single_Cycle_32bits_processor/src/prj/MIPS_CPU.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths e:/Github/xupsh/Basys3-Git/Projects_2016.2/1_Logic_Design/3_State_Machine/Single_Cycle_32bits_processor/src/IPCatalog [current_project]
add_files e:/Github/xupsh/Basys3-Git/Projects_2016.2/1_Logic_Design/3_State_Machine/Single_Cycle_32bits_processor/src/prj/MIPS_CPU.srcs/sources_1/bd/MIPS_CPU/MIPS_CPU.bd
set_property used_in_implementation false [get_files -all e:/Github/xupsh/Basys3-Git/Projects_2016.2/1_Logic_Design/3_State_Machine/Single_Cycle_32bits_processor/src/prj/MIPS_CPU.srcs/sources_1/bd/MIPS_CPU/ip/MIPS_CPU_clk_wiz_0_0/MIPS_CPU_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/Github/xupsh/Basys3-Git/Projects_2016.2/1_Logic_Design/3_State_Machine/Single_Cycle_32bits_processor/src/prj/MIPS_CPU.srcs/sources_1/bd/MIPS_CPU/ip/MIPS_CPU_clk_wiz_0_0/MIPS_CPU_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/Github/xupsh/Basys3-Git/Projects_2016.2/1_Logic_Design/3_State_Machine/Single_Cycle_32bits_processor/src/prj/MIPS_CPU.srcs/sources_1/bd/MIPS_CPU/ip/MIPS_CPU_clk_wiz_0_0/MIPS_CPU_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Github/xupsh/Basys3-Git/Projects_2016.2/1_Logic_Design/3_State_Machine/Single_Cycle_32bits_processor/src/prj/MIPS_CPU.srcs/sources_1/bd/MIPS_CPU/MIPS_CPU_ooc.xdc]
set_property is_locked true [get_files e:/Github/xupsh/Basys3-Git/Projects_2016.2/1_Logic_Design/3_State_Machine/Single_Cycle_32bits_processor/src/prj/MIPS_CPU.srcs/sources_1/bd/MIPS_CPU/MIPS_CPU.bd]

read_verilog -library xil_defaultlib e:/Github/xupsh/Basys3-Git/Projects_2016.2/1_Logic_Design/3_State_Machine/Single_Cycle_32bits_processor/src/prj/MIPS_CPU.srcs/sources_1/imports/hdl/MIPS_CPU_wrapper.v
read_xdc e:/Github/xupsh/Basys3-Git/Projects_2016.2/1_Logic_Design/3_State_Machine/Single_Cycle_32bits_processor/src/prj/MIPS_CPU.srcs/constrs_1/imports/Constraint/MIPS_CPU.xdc
set_property used_in_implementation false [get_files e:/Github/xupsh/Basys3-Git/Projects_2016.2/1_Logic_Design/3_State_Machine/Single_Cycle_32bits_processor/src/prj/MIPS_CPU.srcs/constrs_1/imports/Constraint/MIPS_CPU.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
catch { write_hwdef -file MIPS_CPU_wrapper.hwdef }
synth_design -top MIPS_CPU_wrapper -part xc7a35tcpg236-1
write_checkpoint -noxdef MIPS_CPU_wrapper.dcp
catch { report_utilization -file MIPS_CPU_wrapper_utilization_synth.rpt -pb MIPS_CPU_wrapper_utilization_synth.pb }
