#seven segment display 
set_property PACKAGE_PIN W7 [get_ports {seg[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[7]}]
set_property PACKAGE_PIN W6 [get_ports {seg[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[6]}]
set_property PACKAGE_PIN U8 [get_ports {seg[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[5]}]
set_property PACKAGE_PIN V8 [get_ports {seg[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[4]}]
set_property PACKAGE_PIN U5 [get_ports {seg[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[3]}]
set_property PACKAGE_PIN V5 [get_ports {seg[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[2]}]
set_property PACKAGE_PIN U7 [get_ports {seg[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[1]}]

set_property PACKAGE_PIN V7 [get_ports {seg[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[0]}]

set_property PACKAGE_PIN U2 [get_ports {seg[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[8]}]
set_property PACKAGE_PIN U4 [get_ports {seg[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[9]}]
set_property PACKAGE_PIN V4 [get_ports {seg[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[10]}]
set_property PACKAGE_PIN W4 [get_ports {seg[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[11]}]

#clock
set_property PACKAGE_PIN W5 [get_ports clk100]
set_property IOSTANDARD LVCMOS33 [get_ports clk100]

set_property PACKAGE_PIN W17 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property PACKAGE_PIN V17 [get_ports temp_stop]
set_property IOSTANDARD LVCMOS33 [get_ports temp_stop]
set_property PACKAGE_PIN V16 [get_ports completion]
set_property IOSTANDARD LVCMOS33 [get_ports completion]
set_property PACKAGE_PIN W16 [get_ports check_total]
set_property IOSTANDARD LVCMOS33 [get_ports check_total]

#sw
#set_property PACKAGE_PIN W14 [get_ports {sw[0]}]
#set_property PACKAGE_PIN W13 [get_ports {sw[1]}]
#set_property PACKAGE_PIN V2 [get_ports {sw[2]}]
#set_property PACKAGE_PIN T3 [get_ports {sw[3]}]
#set_property PACKAGE_PIN T2 [get_ports {sw[4]}]
#set_property PACKAGE_PIN R3 [get_ports {sw[5]}]
#set_property PACKAGE_PIN W2 [get_ports {sw[6]}]
#set_property PACKAGE_PIN U1 [get_ports {sw[7]}]
#set_property PACKAGE_PIN T1 [get_ports {sw[8]}]
#set_property PACKAGE_PIN R2 [get_ports {sw[9]}]

#set_property IOSTANDARD LVCMOS33 [get_ports {sw[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sw[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sw[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sw[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sw[4]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sw[5]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sw[6]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sw[7]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sw[8]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sw[9]}]


#led
set_property PACKAGE_PIN U16 [get_ports {led[0]}]
set_property PACKAGE_PIN E19 [get_ports {led[1]}]
set_property PACKAGE_PIN U19 [get_ports {led[2]}]
set_property PACKAGE_PIN V19 [get_ports {led[3]}]
set_property PACKAGE_PIN W18 [get_ports {led[4]}]
set_property PACKAGE_PIN L1 [get_ports led11]

set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports led11]


