# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Constraint/oscilloscope.xdc

# IP: ip/debounce_0/debounce_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==debounce_0 || ORIG_REF_NAME==debounce_0}]

# IP: ip/vga_0/vga_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vga_0 || ORIG_REF_NAME==vga_0}]

# IP: ip/xadc_0/xadc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xadc_0 || ORIG_REF_NAME==xadc_0}]
