# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Constraint/B3_Balltrack.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1}]

# IP: bd/design_1/ip/design_1_IICctrl_0_0/design_1_IICctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_IICctrl_0_0 || ORIG_REF_NAME==design_1_IICctrl_0_0}]

# IP: bd/design_1/ip/design_1_PWM_gen_0_0/design_1_PWM_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_PWM_gen_0_0 || ORIG_REF_NAME==design_1_PWM_gen_0_0}]

# IP: bd/design_1/ip/design_1_PWM_gen_1_0/design_1_PWM_gen_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_PWM_gen_1_0 || ORIG_REF_NAME==design_1_PWM_gen_1_0}]

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_0/design_1_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_0 || ORIG_REF_NAME==design_1_blk_mem_gen_0_0}]

# IP: bd/design_1/ip/design_1_cam_ov7670_ov7725_0_0/design_1_cam_ov7670_ov7725_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_cam_ov7670_ov7725_0_0 || ORIG_REF_NAME==design_1_cam_ov7670_ov7725_0_0}]

# IP: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0}]

# IP: bd/design_1/ip/design_1_colorDetect_0_0/design_1_colorDetect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_colorDetect_0_0 || ORIG_REF_NAME==design_1_colorDetect_0_0}]

# IP: bd/design_1/ip/design_1_debounce_0_0/design_1_debounce_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_debounce_0_0 || ORIG_REF_NAME==design_1_debounce_0_0}]

# IP: bd/design_1/ip/design_1_dilate_0_0/design_1_dilate_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_dilate_0_0 || ORIG_REF_NAME==design_1_dilate_0_0}]

# IP: bd/design_1/ip/design_1_erode_0_0/design_1_erode_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_erode_0_0 || ORIG_REF_NAME==design_1_erode_0_0}]

# IP: bd/design_1/ip/design_1_move_en_0_0/design_1_move_en_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_move_en_0_0 || ORIG_REF_NAME==design_1_move_en_0_0}]

# IP: bd/design_1/ip/design_1_move_en_1_0/design_1_move_en_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_move_en_1_0 || ORIG_REF_NAME==design_1_move_en_1_0}]

# IP: bd/design_1/ip/design_1_ov7725_regData_0_0/design_1_ov7725_regData_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ov7725_regData_0_0 || ORIG_REF_NAME==design_1_ov7725_regData_0_0}]

# IP: bd/design_1/ip/design_1_ram_read_0_0/design_1_ram_read_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ram_read_0_0 || ORIG_REF_NAME==design_1_ram_read_0_0}]

# IP: bd/design_1/ip/design_1_region_cut_0_0/design_1_region_cut_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_region_cut_0_0 || ORIG_REF_NAME==design_1_region_cut_0_0}]

# IP: bd/design_1/ip/design_1_rgb2hsv_top_0_0/design_1_rgb2hsv_top_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rgb2hsv_top_0_0 || ORIG_REF_NAME==design_1_rgb2hsv_top_0_0}]

# IP: bd/design_1/ip/design_1_rgb565_rgb888_0_0/design_1_rgb565_rgb888_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rgb565_rgb888_0_0 || ORIG_REF_NAME==design_1_rgb565_rgb888_0_0}]

# IP: bd/design_1/ip/design_1_rgb888_rgb565_0_0/design_1_rgb888_rgb565_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rgb888_rgb565_0_0 || ORIG_REF_NAME==design_1_rgb888_rgb565_0_0}]

# IP: bd/design_1/ip/design_1_servo_ctrl_0_0/design_1_servo_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_servo_ctrl_0_0 || ORIG_REF_NAME==design_1_servo_ctrl_0_0}]

# IP: bd/design_1/ip/design_1_vga_0_0/design_1_vga_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_vga_0_0 || ORIG_REF_NAME==design_1_vga_0_0}]

# IP: bd/design_1/ip/design_1_xadc_0_0/design_1_xadc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xadc_0_0 || ORIG_REF_NAME==design_1_xadc_0_0}]

# IP: bd/design_1/ip/design_1_xadc_0_0/ip/xadc_wiz_0/xadc_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xadc_wiz_0 || ORIG_REF_NAME==xadc_wiz_0}]

# IP: bd/design_1/ip/design_1_xlconstant_0_0/design_1_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_0 || ORIG_REF_NAME==design_1_xlconstant_0_0}]

# XDC: bd/design_1/ip/design_1_blk_mem_gen_0_0/design_1_blk_mem_gen_0_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_xadc_0_0/ip/xadc_wiz_0/xadc_wiz_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_xadc_0_0/ip/xadc_wiz_0/xadc_wiz_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==xadc_wiz_0 || ORIG_REF_NAME==xadc_wiz_0}] {/inst }]/inst ]]

# XDC: bd/design_1/design_1_ooc.xdc
