# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Constraint/B3_sobel.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1}]

# IP: bd/design_1/ip/design_1_IICctrl_0_0/design_1_IICctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_IICctrl_0_0 || ORIG_REF_NAME==design_1_IICctrl_0_0}]

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_0/design_1_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_0 || ORIG_REF_NAME==design_1_blk_mem_gen_0_0}]

# IP: bd/design_1/ip/design_1_cam_ov7670_ov7725_0_0/design_1_cam_ov7670_ov7725_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_cam_ov7670_ov7725_0_0 || ORIG_REF_NAME==design_1_cam_ov7670_ov7725_0_0}]

# IP: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0}]

# IP: bd/design_1/ip/design_1_debounce_0_0/design_1_debounce_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_debounce_0_0 || ORIG_REF_NAME==design_1_debounce_0_0}]

# IP: bd/design_1/ip/design_1_ov7725_regData_0_0/design_1_ov7725_regData_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ov7725_regData_0_0 || ORIG_REF_NAME==design_1_ov7725_regData_0_0}]

# IP: bd/design_1/ip/design_1_ram_read_0_0/design_1_ram_read_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ram_read_0_0 || ORIG_REF_NAME==design_1_ram_read_0_0}]

# IP: bd/design_1/ip/design_1_region_cut_0_0/design_1_region_cut_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_region_cut_0_0 || ORIG_REF_NAME==design_1_region_cut_0_0}]

# IP: bd/design_1/ip/design_1_rgb565_rgb888_0_0/design_1_rgb565_rgb888_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rgb565_rgb888_0_0 || ORIG_REF_NAME==design_1_rgb565_rgb888_0_0}]

# IP: bd/design_1/ip/design_1_rgb888_rgb565_0_0/design_1_rgb888_rgb565_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rgb888_rgb565_0_0 || ORIG_REF_NAME==design_1_rgb888_rgb565_0_0}]

# IP: bd/design_1/ip/design_1_sobel_0_0/design_1_sobel_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sobel_0_0 || ORIG_REF_NAME==design_1_sobel_0_0}]

# IP: bd/design_1/ip/design_1_vga_0_0/design_1_vga_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_vga_0_0 || ORIG_REF_NAME==design_1_vga_0_0}]

# IP: bd/design_1/ip/design_1_xlconstant_0_0/design_1_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_0 || ORIG_REF_NAME==design_1_xlconstant_0_0}]

# XDC: bd/design_1/ip/design_1_blk_mem_gen_0_0/design_1_blk_mem_gen_0_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_ooc.xdc

# XDC: bd/design_1/design_1_ooc.xdc
