# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7a35tcpg236-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir e:/Github/new/yuehan/tcl_project/taxi/src/prj/taxi.cache/wt [current_project]
set_property parent.project_path e:/Github/new/yuehan/tcl_project/taxi/src/prj/taxi.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  e:/Github/new/yuehan/tcl_project/taxi/src/prj/taxi.srcs/sources_1/imports/HDL_source/bcd.v
  e:/Github/new/yuehan/tcl_project/taxi/src/prj/taxi.srcs/sources_1/imports/HDL_source/taxi.v
  e:/Github/new/yuehan/tcl_project/taxi/src/prj/taxi.srcs/sources_1/imports/HDL_source/seg_display.v
  e:/Github/new/yuehan/tcl_project/taxi/src/prj/taxi.srcs/sources_1/imports/HDL_source/top.v
}
read_xdc e:/Github/new/yuehan/tcl_project/taxi/src/prj/taxi.srcs/constrs_1/imports/Constraint/taxi.xdc
set_property used_in_implementation false [get_files e:/Github/new/yuehan/tcl_project/taxi/src/prj/taxi.srcs/constrs_1/imports/Constraint/taxi.xdc]

catch { write_hwdef -file top.hwdef }
synth_design -top top -part xc7a35tcpg236-1
write_checkpoint -noxdef top.dcp
catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
