webtalk_init -webtalk_dir E:\\Basys3\\Microblaze\\oled\\MB_Uart.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "星期五 二月 12 21:37:56 2016" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2014.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2014.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "12589_7792_1448951788_326" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "t73t1qhcj26dcqpkhg9s63pm82" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2014.4_10" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "10" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4610M CPU @ 3.00GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2993 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1454480940079" -context "sdk\\\\hardware/1454480940079"
webtalk_add_data -client sdk -key isZynq -value "false" -context "sdk\\\\hardware/1454480940079"
webtalk_add_data -client sdk -key Processors -value "1" -context "sdk\\\\hardware/1454480940079"
webtalk_add_data -client sdk -key VivadoVersion -value "2014.4" -context "sdk\\\\hardware/1454480940079"
webtalk_add_data -client sdk -key Arch -value "artix7" -context "sdk\\\\hardware/1454480940079"
webtalk_add_data -client sdk -key Device -value "7a35t" -context "sdk\\\\hardware/1454480940079"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1454480940079"
webtalk_add_data -client sdk -key uid -value "1454480956123" -context "sdk\\\\bsp/1454480956123"
webtalk_add_data -client sdk -key hwid -value "1454480940079" -context "sdk\\\\bsp/1454480956123"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1454480956123"
webtalk_add_data -client sdk -key apptemplate -value "peripheral_tests" -context "sdk\\\\bsp/1454480956123"
webtalk_add_data -client sdk -key uid -value "1454480957772" -context "sdk\\\\application/1454480957772"
webtalk_add_data -client sdk -key hwid -value "1454480940079" -context "sdk\\\\application/1454480957772"
webtalk_add_data -client sdk -key bspid -value "1454480956123" -context "sdk\\\\application/1454480957772"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1454480957772"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1454480957772"
webtalk_add_data -client sdk -key apptemplate -value "peripheral_tests" -context "sdk\\\\application/1454480957772"
webtalk_transmit -clientid 550712412 -regid "12589_7792_1448951788_326" -xml E:\\Basys3\\Microblaze\\oled\\MB_Uart.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html E:\\Basys3\\Microblaze\\oled\\MB_Uart.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm E:\\Basys3\\Microblaze\\oled\\MB_Uart.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
