// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "sobel_filter.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic sobel_filter::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic sobel_filter::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<3> sobel_filter::ap_ST_st1_fsm_0 = "1";
const sc_lv<3> sobel_filter::ap_ST_st2_fsm_1 = "10";
const sc_lv<3> sobel_filter::ap_ST_pp0_stg0_fsm_2 = "100";
const bool sobel_filter::ap_true = true;
const sc_lv<32> sobel_filter::ap_const_lv32_2 = "10";
const sc_lv<1> sobel_filter::ap_const_lv1_1 = "1";
const sc_lv<32> sobel_filter::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> sobel_filter::ap_const_lv32_1 = "1";
const sc_lv<1> sobel_filter::ap_const_lv1_0 = "0";
const sc_lv<31> sobel_filter::ap_const_lv31_0 = "0000000000000000000000000000000";
const sc_lv<24> sobel_filter::ap_const_lv24_0 = "000000000000000000000000";
const sc_lv<31> sobel_filter::ap_const_lv31_1 = "1";
const sc_lv<11> sobel_filter::ap_const_lv11_0 = "00000000000";
const sc_lv<7> sobel_filter::ap_const_lv7_0 = "0000000";
const sc_lv<32> sobel_filter::ap_const_lv32_FFFFFFFF = "11111111111111111111111111111111";
const sc_lv<22> sobel_filter::ap_const_lv22_3FFFFF = "1111111111111111111111";
const sc_lv<32> sobel_filter::ap_const_lv32_8 = "1000";
const sc_lv<32> sobel_filter::ap_const_lv32_F = "1111";
const sc_lv<32> sobel_filter::ap_const_lv32_10 = "10000";
const sc_lv<32> sobel_filter::ap_const_lv32_17 = "10111";
const sc_lv<6> sobel_filter::ap_const_lv6_0 = "000000";
const sc_lv<13> sobel_filter::ap_const_lv13_19 = "11001";
const sc_lv<9> sobel_filter::ap_const_lv9_80 = "10000000";
const sc_lv<8> sobel_filter::ap_const_lv8_10 = "10000";

sobel_filter::sobel_filter(sc_module_name name) : sc_module(name), mVcdFile(0) {
    buff_A_M_0_U = new sobel_filter_buff_A_M_0("buff_A_M_0_U");
    buff_A_M_0_U->clk(ap_clk);
    buff_A_M_0_U->reset(ap_rst);
    buff_A_M_0_U->address0(buff_A_M_0_address0);
    buff_A_M_0_U->ce0(buff_A_M_0_ce0);
    buff_A_M_0_U->q0(buff_A_M_0_q0);
    buff_A_M_0_U->address1(buff_A_M_0_address1);
    buff_A_M_0_U->ce1(buff_A_M_0_ce1);
    buff_A_M_0_U->we1(buff_A_M_0_we1);
    buff_A_M_0_U->d1(buff_A_M_0_d1);
    buff_A_M_1_U = new sobel_filter_buff_A_M_1("buff_A_M_1_U");
    buff_A_M_1_U->clk(ap_clk);
    buff_A_M_1_U->reset(ap_rst);
    buff_A_M_1_U->address0(buff_A_M_1_address0);
    buff_A_M_1_U->ce0(buff_A_M_1_ce0);
    buff_A_M_1_U->we0(buff_A_M_1_we0);
    buff_A_M_1_U->d0(buff_A_M_1_d0);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ColIndex_assign_cast_fu_291_p1);
    sensitive << ( ColIndex_assign_phi_fu_179_p4 );

    SC_METHOD(thread_ColIndex_assign_phi_fu_179_p4);
    sensitive << ( ColIndex_assign_reg_175 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( tmp_8_reg_553 );
    sensitive << ( col_reg_557 );

    SC_METHOD(thread_ap_sig_bdd_34);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_53);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_68);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_cseq_ST_pp0_stg0_fsm_2);
    sensitive << ( ap_sig_bdd_34 );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_bdd_53 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm_1);
    sensitive << ( ap_sig_bdd_68 );

    SC_METHOD(thread_buff_A_M_0_address0);
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( tmp_s_fu_361_p1 );

    SC_METHOD(thread_buff_A_M_0_address1);
    sensitive << ( ap_reg_ppiten_pp0_it3 );
    sensitive << ( tmp_12_fu_366_p1 );

    SC_METHOD(thread_buff_A_M_0_ce0);
    sensitive << ( ap_reg_ppiten_pp0_it2 );

    SC_METHOD(thread_buff_A_M_0_ce1);
    sensitive << ( ap_reg_ppiten_pp0_it3 );

    SC_METHOD(thread_buff_A_M_0_d1);
    sensitive << ( ap_reg_ppiten_pp0_it3 );
    sensitive << ( tmp_31_i_fu_487_p4 );

    SC_METHOD(thread_buff_A_M_0_we1);
    sensitive << ( ap_reg_ppiten_pp0_it3 );
    sensitive << ( ap_reg_ppstg_tmp_11_reg_566_pp0_it2 );

    SC_METHOD(thread_buff_A_M_1_address0);
    sensitive << ( ap_reg_ppiten_pp0_it3 );
    sensitive << ( tmp_s_reg_584 );

    SC_METHOD(thread_buff_A_M_1_ce0);
    sensitive << ( ap_reg_ppiten_pp0_it3 );

    SC_METHOD(thread_buff_A_M_1_d0);
    sensitive << ( ap_reg_ppiten_pp0_it3 );
    sensitive << ( buff_A_M_0_q0 );

    SC_METHOD(thread_buff_A_M_1_we0);
    sensitive << ( ap_reg_ppiten_pp0_it3 );
    sensitive << ( ap_reg_ppstg_tmp_9_reg_562_pp0_it2 );

    SC_METHOD(thread_col_fu_300_p2);
    sensitive << ( ColIndex_assign_phi_fu_179_p4 );

    SC_METHOD(thread_inter_pix_V_address0);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( tmp_20_cast_fu_325_p1 );

    SC_METHOD(thread_inter_pix_V_ce0);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( ap_reg_ppiten_pp0_it3 );

    SC_METHOD(thread_or_cond_fu_336_p2);
    sensitive << ( tmp_5_reg_543 );
    sensitive << ( tmp_15_fu_330_p2 );

    SC_METHOD(thread_out_pix_V_address0);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( tmp_24_cast_fu_356_p1 );

    SC_METHOD(thread_out_pix_V_ce0);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_out_pix_V_d0);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );

    SC_METHOD(thread_out_pix_V_we0);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( tmp_8_fu_295_p2 );
    sensitive << ( or_cond_fu_336_p2 );

    SC_METHOD(thread_p_Val2_3_fu_375_p4);
    sensitive << ( inter_pix_V_q0 );

    SC_METHOD(thread_p_shl1_cast_fu_277_p3);
    sensitive << ( tmp_16_fu_273_p1 );

    SC_METHOD(thread_p_shl1_i_cast_fu_403_p1);
    sensitive << ( p_shl1_i_fu_395_p3 );

    SC_METHOD(thread_p_shl1_i_fu_395_p3);
    sensitive << ( tmp_20_fu_385_p4 );

    SC_METHOD(thread_p_shl2_cast_fu_223_p3);
    sensitive << ( tmp_4_fu_219_p1 );

    SC_METHOD(thread_p_shl2_i_cast_fu_415_p1);
    sensitive << ( p_shl2_i_fu_407_p3 );

    SC_METHOD(thread_p_shl2_i_fu_407_p3);
    sensitive << ( tmp_20_fu_385_p4 );

    SC_METHOD(thread_p_shl3_cast_fu_235_p3);
    sensitive << ( tmp_7_fu_231_p1 );

    SC_METHOD(thread_p_shl_cast_fu_265_p3);
    sensitive << ( tmp_14_fu_261_p1 );

    SC_METHOD(thread_p_shl_i_cast_fu_431_p1);
    sensitive << ( p_shl_i_fu_423_p3 );

    SC_METHOD(thread_p_shl_i_fu_423_p3);
    sensitive << ( p_Val2_3_fu_375_p4 );

    SC_METHOD(thread_r_V_fu_371_p1);
    sensitive << ( inter_pix_V_q0 );

    SC_METHOD(thread_row_1_fu_208_p2);
    sensitive << ( row_reg_164 );

    SC_METHOD(thread_row_cast_fu_199_p1);
    sensitive << ( row_reg_164 );

    SC_METHOD(thread_tmp1_fu_455_p2);
    sensitive << ( tmp2_cast_fu_451_p1 );
    sensitive << ( p_shl_i_cast_fu_431_p1 );

    SC_METHOD(thread_tmp2_cast_fu_451_p1);
    sensitive << ( tmp2_fu_445_p2 );

    SC_METHOD(thread_tmp2_fu_445_p2);
    sensitive << ( p_shl2_i_cast_fu_415_p1 );
    sensitive << ( p_shl1_i_cast_fu_403_p1 );

    SC_METHOD(thread_tmp3_cast_fu_477_p1);
    sensitive << ( tmp3_fu_471_p2 );

    SC_METHOD(thread_tmp3_fu_471_p2);
    sensitive << ( tmp4_cast_fu_467_p1 );
    sensitive << ( tmp_26_i_fu_439_p2 );

    SC_METHOD(thread_tmp4_cast_fu_467_p1);
    sensitive << ( tmp4_fu_461_p2 );

    SC_METHOD(thread_tmp4_fu_461_p2);
    sensitive << ( tmp_23_i_cast5_fu_419_p1 );

    SC_METHOD(thread_tmp_11_fu_311_p2);
    sensitive << ( tmp_3_reg_533 );
    sensitive << ( tmp_9_fu_306_p2 );

    SC_METHOD(thread_tmp_12_fu_366_p1);
    sensitive << ( ap_reg_ppstg_ColIndex_assign_reg_175_pp0_it2 );

    SC_METHOD(thread_tmp_13_fu_243_p2);
    sensitive << ( p_shl2_cast_fu_223_p3 );
    sensitive << ( p_shl3_cast_fu_235_p3 );

    SC_METHOD(thread_tmp_14_fu_261_p1);
    sensitive << ( tmp_6_fu_255_p2 );

    SC_METHOD(thread_tmp_15_fu_330_p2);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( tmp_8_fu_295_p2 );
    sensitive << ( ColIndex_assign_phi_fu_179_p4 );

    SC_METHOD(thread_tmp_16_fu_273_p1);
    sensitive << ( tmp_6_fu_255_p2 );

    SC_METHOD(thread_tmp_17_fu_285_p2);
    sensitive << ( p_shl_cast_fu_265_p3 );
    sensitive << ( p_shl1_cast_fu_277_p3 );

    SC_METHOD(thread_tmp_18_fu_316_p1);
    sensitive << ( ColIndex_assign_phi_fu_179_p4 );

    SC_METHOD(thread_tmp_19_fu_320_p2);
    sensitive << ( tmp_13_reg_538 );
    sensitive << ( tmp_18_fu_316_p1 );

    SC_METHOD(thread_tmp_1_fu_193_p2);
    sensitive << ( cols );

    SC_METHOD(thread_tmp_20_cast_fu_325_p1);
    sensitive << ( tmp_19_fu_320_p2 );

    SC_METHOD(thread_tmp_20_fu_385_p4);
    sensitive << ( inter_pix_V_q0 );

    SC_METHOD(thread_tmp_21_fu_341_p1);
    sensitive << ( ColIndex_assign_phi_fu_179_p4 );

    SC_METHOD(thread_tmp_22_fu_345_p2);
    sensitive << ( tmp_21_fu_341_p1 );

    SC_METHOD(thread_tmp_23_fu_351_p2);
    sensitive << ( tmp_17_reg_548 );
    sensitive << ( tmp_22_fu_345_p2 );

    SC_METHOD(thread_tmp_23_i_cast5_fu_419_p1);
    sensitive << ( p_Val2_3_fu_375_p4 );

    SC_METHOD(thread_tmp_24_cast_fu_356_p1);
    sensitive << ( tmp_23_fu_351_p2 );

    SC_METHOD(thread_tmp_26_i_fu_439_p1);
    sensitive << ( ap_reg_ppiten_pp0_it3 );
    sensitive << ( tmp_26_i_fu_439_p10 );

    SC_METHOD(thread_tmp_26_i_fu_439_p10);
    sensitive << ( r_V_fu_371_p1 );

    SC_METHOD(thread_tmp_26_i_fu_439_p2);
    sensitive << ( tmp_26_i_fu_439_p1 );

    SC_METHOD(thread_tmp_29_i_fu_481_p2);
    sensitive << ( tmp3_cast_fu_477_p1 );
    sensitive << ( tmp1_fu_455_p2 );

    SC_METHOD(thread_tmp_2_fu_203_p2);
    sensitive << ( tmp_reg_514 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( row_cast_fu_199_p1 );

    SC_METHOD(thread_tmp_31_i_fu_487_p4);
    sensitive << ( tmp_29_i_fu_481_p2 );

    SC_METHOD(thread_tmp_3_fu_214_p2);
    sensitive << ( rows );
    sensitive << ( tmp_2_fu_203_p2 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( row_cast_fu_199_p1 );

    SC_METHOD(thread_tmp_4_fu_219_p1);
    sensitive << ( row_reg_164 );

    SC_METHOD(thread_tmp_5_fu_249_p2);
    sensitive << ( tmp_2_fu_203_p2 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( row_reg_164 );

    SC_METHOD(thread_tmp_6_fu_255_p2);
    sensitive << ( row_cast_fu_199_p1 );

    SC_METHOD(thread_tmp_7_fu_231_p1);
    sensitive << ( row_reg_164 );

    SC_METHOD(thread_tmp_8_fu_295_p2);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( tmp_1_reg_519 );
    sensitive << ( ColIndex_assign_cast_fu_291_p1 );

    SC_METHOD(thread_tmp_9_fu_306_p2);
    sensitive << ( cols );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( tmp_8_fu_295_p2 );
    sensitive << ( ColIndex_assign_cast_fu_291_p1 );

    SC_METHOD(thread_tmp_fu_187_p2);
    sensitive << ( rows );

    SC_METHOD(thread_tmp_s_fu_361_p1);
    sensitive << ( ap_reg_ppstg_ColIndex_assign_reg_175_pp0_it1 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( ap_reg_ppiten_pp0_it3 );
    sensitive << ( tmp_2_fu_203_p2 );
    sensitive << ( tmp_8_fu_295_p2 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "001";
    ap_reg_ppiten_pp0_it0 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it1 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it2 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it3 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "sobel_filter_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, inter_pix_V_address0, "(port)inter_pix_V_address0");
    sc_trace(mVcdFile, inter_pix_V_ce0, "(port)inter_pix_V_ce0");
    sc_trace(mVcdFile, inter_pix_V_q0, "(port)inter_pix_V_q0");
    sc_trace(mVcdFile, out_pix_V_address0, "(port)out_pix_V_address0");
    sc_trace(mVcdFile, out_pix_V_ce0, "(port)out_pix_V_ce0");
    sc_trace(mVcdFile, out_pix_V_we0, "(port)out_pix_V_we0");
    sc_trace(mVcdFile, out_pix_V_d0, "(port)out_pix_V_d0");
    sc_trace(mVcdFile, rows, "(port)rows");
    sc_trace(mVcdFile, cols, "(port)cols");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ColIndex_assign_reg_175, "ColIndex_assign_reg_175");
    sc_trace(mVcdFile, ap_reg_ppstg_ColIndex_assign_reg_175_pp0_it1, "ap_reg_ppstg_ColIndex_assign_reg_175_pp0_it1");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_pp0_stg0_fsm_2, "ap_sig_cseq_ST_pp0_stg0_fsm_2");
    sc_trace(mVcdFile, ap_sig_bdd_34, "ap_sig_bdd_34");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it0, "ap_reg_ppiten_pp0_it0");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it1, "ap_reg_ppiten_pp0_it1");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it2, "ap_reg_ppiten_pp0_it2");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it3, "ap_reg_ppiten_pp0_it3");
    sc_trace(mVcdFile, ap_reg_ppstg_ColIndex_assign_reg_175_pp0_it2, "ap_reg_ppstg_ColIndex_assign_reg_175_pp0_it2");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_bdd_53, "ap_sig_bdd_53");
    sc_trace(mVcdFile, tmp_fu_187_p2, "tmp_fu_187_p2");
    sc_trace(mVcdFile, tmp_reg_514, "tmp_reg_514");
    sc_trace(mVcdFile, tmp_1_fu_193_p2, "tmp_1_fu_193_p2");
    sc_trace(mVcdFile, tmp_1_reg_519, "tmp_1_reg_519");
    sc_trace(mVcdFile, tmp_2_fu_203_p2, "tmp_2_fu_203_p2");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm_1, "ap_sig_cseq_ST_st2_fsm_1");
    sc_trace(mVcdFile, ap_sig_bdd_68, "ap_sig_bdd_68");
    sc_trace(mVcdFile, row_1_fu_208_p2, "row_1_fu_208_p2");
    sc_trace(mVcdFile, row_1_reg_528, "row_1_reg_528");
    sc_trace(mVcdFile, tmp_3_fu_214_p2, "tmp_3_fu_214_p2");
    sc_trace(mVcdFile, tmp_3_reg_533, "tmp_3_reg_533");
    sc_trace(mVcdFile, tmp_13_fu_243_p2, "tmp_13_fu_243_p2");
    sc_trace(mVcdFile, tmp_13_reg_538, "tmp_13_reg_538");
    sc_trace(mVcdFile, tmp_5_fu_249_p2, "tmp_5_fu_249_p2");
    sc_trace(mVcdFile, tmp_5_reg_543, "tmp_5_reg_543");
    sc_trace(mVcdFile, tmp_17_fu_285_p2, "tmp_17_fu_285_p2");
    sc_trace(mVcdFile, tmp_17_reg_548, "tmp_17_reg_548");
    sc_trace(mVcdFile, tmp_8_fu_295_p2, "tmp_8_fu_295_p2");
    sc_trace(mVcdFile, tmp_8_reg_553, "tmp_8_reg_553");
    sc_trace(mVcdFile, col_fu_300_p2, "col_fu_300_p2");
    sc_trace(mVcdFile, col_reg_557, "col_reg_557");
    sc_trace(mVcdFile, tmp_9_fu_306_p2, "tmp_9_fu_306_p2");
    sc_trace(mVcdFile, tmp_9_reg_562, "tmp_9_reg_562");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_9_reg_562_pp0_it1, "ap_reg_ppstg_tmp_9_reg_562_pp0_it1");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_9_reg_562_pp0_it2, "ap_reg_ppstg_tmp_9_reg_562_pp0_it2");
    sc_trace(mVcdFile, tmp_11_fu_311_p2, "tmp_11_fu_311_p2");
    sc_trace(mVcdFile, tmp_11_reg_566, "tmp_11_reg_566");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_11_reg_566_pp0_it1, "ap_reg_ppstg_tmp_11_reg_566_pp0_it1");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_11_reg_566_pp0_it2, "ap_reg_ppstg_tmp_11_reg_566_pp0_it2");
    sc_trace(mVcdFile, or_cond_fu_336_p2, "or_cond_fu_336_p2");
    sc_trace(mVcdFile, tmp_s_fu_361_p1, "tmp_s_fu_361_p1");
    sc_trace(mVcdFile, tmp_s_reg_584, "tmp_s_reg_584");
    sc_trace(mVcdFile, buff_A_M_0_address0, "buff_A_M_0_address0");
    sc_trace(mVcdFile, buff_A_M_0_ce0, "buff_A_M_0_ce0");
    sc_trace(mVcdFile, buff_A_M_0_q0, "buff_A_M_0_q0");
    sc_trace(mVcdFile, buff_A_M_0_address1, "buff_A_M_0_address1");
    sc_trace(mVcdFile, buff_A_M_0_ce1, "buff_A_M_0_ce1");
    sc_trace(mVcdFile, buff_A_M_0_we1, "buff_A_M_0_we1");
    sc_trace(mVcdFile, buff_A_M_0_d1, "buff_A_M_0_d1");
    sc_trace(mVcdFile, buff_A_M_1_address0, "buff_A_M_1_address0");
    sc_trace(mVcdFile, buff_A_M_1_ce0, "buff_A_M_1_ce0");
    sc_trace(mVcdFile, buff_A_M_1_we0, "buff_A_M_1_we0");
    sc_trace(mVcdFile, buff_A_M_1_d0, "buff_A_M_1_d0");
    sc_trace(mVcdFile, row_reg_164, "row_reg_164");
    sc_trace(mVcdFile, ColIndex_assign_phi_fu_179_p4, "ColIndex_assign_phi_fu_179_p4");
    sc_trace(mVcdFile, tmp_20_cast_fu_325_p1, "tmp_20_cast_fu_325_p1");
    sc_trace(mVcdFile, tmp_24_cast_fu_356_p1, "tmp_24_cast_fu_356_p1");
    sc_trace(mVcdFile, tmp_12_fu_366_p1, "tmp_12_fu_366_p1");
    sc_trace(mVcdFile, row_cast_fu_199_p1, "row_cast_fu_199_p1");
    sc_trace(mVcdFile, tmp_4_fu_219_p1, "tmp_4_fu_219_p1");
    sc_trace(mVcdFile, tmp_7_fu_231_p1, "tmp_7_fu_231_p1");
    sc_trace(mVcdFile, p_shl2_cast_fu_223_p3, "p_shl2_cast_fu_223_p3");
    sc_trace(mVcdFile, p_shl3_cast_fu_235_p3, "p_shl3_cast_fu_235_p3");
    sc_trace(mVcdFile, tmp_6_fu_255_p2, "tmp_6_fu_255_p2");
    sc_trace(mVcdFile, tmp_14_fu_261_p1, "tmp_14_fu_261_p1");
    sc_trace(mVcdFile, tmp_16_fu_273_p1, "tmp_16_fu_273_p1");
    sc_trace(mVcdFile, p_shl_cast_fu_265_p3, "p_shl_cast_fu_265_p3");
    sc_trace(mVcdFile, p_shl1_cast_fu_277_p3, "p_shl1_cast_fu_277_p3");
    sc_trace(mVcdFile, ColIndex_assign_cast_fu_291_p1, "ColIndex_assign_cast_fu_291_p1");
    sc_trace(mVcdFile, tmp_18_fu_316_p1, "tmp_18_fu_316_p1");
    sc_trace(mVcdFile, tmp_19_fu_320_p2, "tmp_19_fu_320_p2");
    sc_trace(mVcdFile, tmp_15_fu_330_p2, "tmp_15_fu_330_p2");
    sc_trace(mVcdFile, tmp_21_fu_341_p1, "tmp_21_fu_341_p1");
    sc_trace(mVcdFile, tmp_22_fu_345_p2, "tmp_22_fu_345_p2");
    sc_trace(mVcdFile, tmp_23_fu_351_p2, "tmp_23_fu_351_p2");
    sc_trace(mVcdFile, tmp_20_fu_385_p4, "tmp_20_fu_385_p4");
    sc_trace(mVcdFile, p_shl1_i_fu_395_p3, "p_shl1_i_fu_395_p3");
    sc_trace(mVcdFile, p_shl2_i_fu_407_p3, "p_shl2_i_fu_407_p3");
    sc_trace(mVcdFile, p_Val2_3_fu_375_p4, "p_Val2_3_fu_375_p4");
    sc_trace(mVcdFile, p_shl_i_fu_423_p3, "p_shl_i_fu_423_p3");
    sc_trace(mVcdFile, r_V_fu_371_p1, "r_V_fu_371_p1");
    sc_trace(mVcdFile, tmp_26_i_fu_439_p1, "tmp_26_i_fu_439_p1");
    sc_trace(mVcdFile, p_shl2_i_cast_fu_415_p1, "p_shl2_i_cast_fu_415_p1");
    sc_trace(mVcdFile, p_shl1_i_cast_fu_403_p1, "p_shl1_i_cast_fu_403_p1");
    sc_trace(mVcdFile, tmp2_fu_445_p2, "tmp2_fu_445_p2");
    sc_trace(mVcdFile, tmp2_cast_fu_451_p1, "tmp2_cast_fu_451_p1");
    sc_trace(mVcdFile, p_shl_i_cast_fu_431_p1, "p_shl_i_cast_fu_431_p1");
    sc_trace(mVcdFile, tmp_23_i_cast5_fu_419_p1, "tmp_23_i_cast5_fu_419_p1");
    sc_trace(mVcdFile, tmp4_fu_461_p2, "tmp4_fu_461_p2");
    sc_trace(mVcdFile, tmp4_cast_fu_467_p1, "tmp4_cast_fu_467_p1");
    sc_trace(mVcdFile, tmp_26_i_fu_439_p2, "tmp_26_i_fu_439_p2");
    sc_trace(mVcdFile, tmp3_fu_471_p2, "tmp3_fu_471_p2");
    sc_trace(mVcdFile, tmp3_cast_fu_477_p1, "tmp3_cast_fu_477_p1");
    sc_trace(mVcdFile, tmp1_fu_455_p2, "tmp1_fu_455_p2");
    sc_trace(mVcdFile, tmp_29_i_fu_481_p2, "tmp_29_i_fu_481_p2");
    sc_trace(mVcdFile, tmp_31_i_fu_487_p4, "tmp_31_i_fu_487_p4");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, tmp_26_i_fu_439_p10, "tmp_26_i_fu_439_p10");
#endif

    }
    mHdltvinHandle.open("sobel_filter.hdltvin.dat");
    mHdltvoutHandle.open("sobel_filter.hdltvout.dat");
}

sobel_filter::~sobel_filter() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete buff_A_M_0_U;
    delete buff_A_M_1_U;
}

void sobel_filter::thread_ap_clk_no_reset_() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_8_reg_553.read()))) {
        ColIndex_assign_reg_175 = col_reg_557.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                !esl_seteq<1,1,1>(tmp_2_fu_203_p2.read(), ap_const_lv1_0))) {
        ColIndex_assign_reg_175 = ap_const_lv31_0;
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
             esl_seteq<1,1,1>(ap_const_lv1_0, tmp_8_fu_295_p2.read()))) {
            ap_reg_ppiten_pp0_it0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                    !esl_seteq<1,1,1>(tmp_2_fu_203_p2.read(), ap_const_lv1_0))) {
            ap_reg_ppiten_pp0_it0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
             !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_8_fu_295_p2.read()))) {
            ap_reg_ppiten_pp0_it1 = ap_const_logic_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                     !esl_seteq<1,1,1>(tmp_2_fu_203_p2.read(), ap_const_lv1_0)) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
                     esl_seteq<1,1,1>(ap_const_lv1_0, tmp_8_fu_295_p2.read())))) {
            ap_reg_ppiten_pp0_it1 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_true, ap_true)) {
            ap_reg_ppiten_pp0_it2 = ap_reg_ppiten_pp0_it1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it3 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_true, ap_true)) {
            ap_reg_ppiten_pp0_it3 = ap_reg_ppiten_pp0_it2.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                    !esl_seteq<1,1,1>(tmp_2_fu_203_p2.read(), ap_const_lv1_0))) {
            ap_reg_ppiten_pp0_it3 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_8_fu_295_p2.read()))) {
        row_reg_164 = row_1_reg_528.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read())) {
        row_reg_164 = ap_const_lv31_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read())) {
        ap_reg_ppstg_ColIndex_assign_reg_175_pp0_it1 = ColIndex_assign_reg_175.read();
        ap_reg_ppstg_tmp_11_reg_566_pp0_it1 = tmp_11_reg_566.read();
        ap_reg_ppstg_tmp_9_reg_562_pp0_it1 = tmp_9_reg_562.read();
        tmp_8_reg_553 = tmp_8_fu_295_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_true, ap_true)) {
        ap_reg_ppstg_ColIndex_assign_reg_175_pp0_it2 = ap_reg_ppstg_ColIndex_assign_reg_175_pp0_it1.read();
        ap_reg_ppstg_tmp_11_reg_566_pp0_it2 = ap_reg_ppstg_tmp_11_reg_566_pp0_it1.read();
        ap_reg_ppstg_tmp_9_reg_562_pp0_it2 = ap_reg_ppstg_tmp_9_reg_562_pp0_it1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()))) {
        col_reg_557 = col_fu_300_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        row_1_reg_528 = row_1_fu_208_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_8_fu_295_p2.read()))) {
        tmp_11_reg_566 = tmp_11_fu_311_p2.read();
        tmp_9_reg_562 = tmp_9_fu_306_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && !esl_seteq<1,1,1>(tmp_2_fu_203_p2.read(), ap_const_lv1_0))) {
        tmp_13_reg_538 = tmp_13_fu_243_p2.read();
        tmp_17_reg_548 = tmp_17_fu_285_p2.read();
        tmp_3_reg_533 = tmp_3_fu_214_p2.read();
        tmp_5_reg_543 = tmp_5_fu_249_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read())) {
        tmp_1_reg_519 = tmp_1_fu_193_p2.read();
        tmp_reg_514 = tmp_fu_187_p2.read();
    }
    if (!esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_tmp_9_reg_562_pp0_it1.read())) {
        tmp_s_reg_584 = tmp_s_fu_361_p1.read();
    }
}

void sobel_filter::thread_ColIndex_assign_cast_fu_291_p1() {
    ColIndex_assign_cast_fu_291_p1 = esl_zext<32,31>(ColIndex_assign_phi_fu_179_p4.read());
}

void sobel_filter::thread_ColIndex_assign_phi_fu_179_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_8_reg_553.read()))) {
        ColIndex_assign_phi_fu_179_p4 = col_reg_557.read();
    } else {
        ColIndex_assign_phi_fu_179_p4 = ColIndex_assign_reg_175.read();
    }
}

void sobel_filter::thread_ap_sig_bdd_34() {
    ap_sig_bdd_34 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(2, 2), ap_const_lv1_1);
}

void sobel_filter::thread_ap_sig_bdd_53() {
    ap_sig_bdd_53 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(0, 0));
}

void sobel_filter::thread_ap_sig_bdd_68() {
    ap_sig_bdd_68 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void sobel_filter::thread_ap_sig_cseq_ST_pp0_stg0_fsm_2() {
    if (ap_sig_bdd_34.read()) {
        ap_sig_cseq_ST_pp0_stg0_fsm_2 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_pp0_stg0_fsm_2 = ap_const_logic_0;
    }
}

void sobel_filter::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_bdd_53.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void sobel_filter::thread_ap_sig_cseq_ST_st2_fsm_1() {
    if (ap_sig_bdd_68.read()) {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    }
}

void sobel_filter::thread_buff_A_M_0_address0() {
    buff_A_M_0_address0 =  (sc_lv<11>) (tmp_s_fu_361_p1.read());
}

void sobel_filter::thread_buff_A_M_0_address1() {
    buff_A_M_0_address1 =  (sc_lv<11>) (tmp_12_fu_366_p1.read());
}

void sobel_filter::thread_buff_A_M_0_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read())) {
        buff_A_M_0_ce0 = ap_const_logic_1;
    } else {
        buff_A_M_0_ce0 = ap_const_logic_0;
    }
}

void sobel_filter::thread_buff_A_M_0_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it3.read())) {
        buff_A_M_0_ce1 = ap_const_logic_1;
    } else {
        buff_A_M_0_ce1 = ap_const_logic_0;
    }
}

void sobel_filter::thread_buff_A_M_0_d1() {
    buff_A_M_0_d1 = (!ap_const_lv8_10.is_01() || !tmp_31_i_fu_487_p4.read().is_01())? sc_lv<8>(): (sc_biguint<8>(ap_const_lv8_10) + sc_biguint<8>(tmp_31_i_fu_487_p4.read()));
}

void sobel_filter::thread_buff_A_M_0_we1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it3.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_tmp_11_reg_566_pp0_it2.read())))) {
        buff_A_M_0_we1 = ap_const_logic_1;
    } else {
        buff_A_M_0_we1 = ap_const_logic_0;
    }
}

void sobel_filter::thread_buff_A_M_1_address0() {
    buff_A_M_1_address0 =  (sc_lv<11>) (tmp_s_reg_584.read());
}

void sobel_filter::thread_buff_A_M_1_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it3.read())) {
        buff_A_M_1_ce0 = ap_const_logic_1;
    } else {
        buff_A_M_1_ce0 = ap_const_logic_0;
    }
}

void sobel_filter::thread_buff_A_M_1_d0() {
    buff_A_M_1_d0 = buff_A_M_0_q0.read();
}

void sobel_filter::thread_buff_A_M_1_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it3.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_tmp_9_reg_562_pp0_it2.read())))) {
        buff_A_M_1_we0 = ap_const_logic_1;
    } else {
        buff_A_M_1_we0 = ap_const_logic_0;
    }
}

void sobel_filter::thread_col_fu_300_p2() {
    col_fu_300_p2 = (!ColIndex_assign_phi_fu_179_p4.read().is_01() || !ap_const_lv31_1.is_01())? sc_lv<31>(): (sc_biguint<31>(ColIndex_assign_phi_fu_179_p4.read()) + sc_biguint<31>(ap_const_lv31_1));
}

void sobel_filter::thread_inter_pix_V_address0() {
    inter_pix_V_address0 =  (sc_lv<21>) (tmp_20_cast_fu_325_p1.read());
}

void sobel_filter::thread_inter_pix_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it3.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        inter_pix_V_ce0 = ap_const_logic_1;
    } else {
        inter_pix_V_ce0 = ap_const_logic_0;
    }
}

void sobel_filter::thread_or_cond_fu_336_p2() {
    or_cond_fu_336_p2 = (tmp_5_reg_543.read() & tmp_15_fu_330_p2.read());
}

void sobel_filter::thread_out_pix_V_address0() {
    out_pix_V_address0 =  (sc_lv<21>) (tmp_24_cast_fu_356_p1.read());
}

void sobel_filter::thread_out_pix_V_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        out_pix_V_ce0 = ap_const_logic_1;
    } else {
        out_pix_V_ce0 = ap_const_logic_0;
    }
}

void sobel_filter::thread_out_pix_V_d0() {
    out_pix_V_d0 = ap_const_lv24_0;
}

void sobel_filter::thread_out_pix_V_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_8_fu_295_p2.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, or_cond_fu_336_p2.read())))) {
        out_pix_V_we0 = ap_const_logic_1;
    } else {
        out_pix_V_we0 = ap_const_logic_0;
    }
}

void sobel_filter::thread_p_Val2_3_fu_375_p4() {
    p_Val2_3_fu_375_p4 = inter_pix_V_q0.read().range(15, 8);
}

void sobel_filter::thread_p_shl1_cast_fu_277_p3() {
    p_shl1_cast_fu_277_p3 = esl_concat<15,7>(tmp_16_fu_273_p1.read(), ap_const_lv7_0);
}

void sobel_filter::thread_p_shl1_i_cast_fu_403_p1() {
    p_shl1_i_cast_fu_403_p1 = esl_zext<15,14>(p_shl1_i_fu_395_p3.read());
}

void sobel_filter::thread_p_shl1_i_fu_395_p3() {
    p_shl1_i_fu_395_p3 = esl_concat<8,6>(tmp_20_fu_385_p4.read(), ap_const_lv6_0);
}

void sobel_filter::thread_p_shl2_cast_fu_223_p3() {
    p_shl2_cast_fu_223_p3 = esl_concat<11,11>(tmp_4_fu_219_p1.read(), ap_const_lv11_0);
}

void sobel_filter::thread_p_shl2_i_cast_fu_415_p1() {
    p_shl2_i_cast_fu_415_p1 = esl_zext<15,9>(p_shl2_i_fu_407_p3.read());
}

void sobel_filter::thread_p_shl2_i_fu_407_p3() {
    p_shl2_i_fu_407_p3 = esl_concat<8,1>(tmp_20_fu_385_p4.read(), ap_const_lv1_0);
}

void sobel_filter::thread_p_shl3_cast_fu_235_p3() {
    p_shl3_cast_fu_235_p3 = esl_concat<15,7>(tmp_7_fu_231_p1.read(), ap_const_lv7_0);
}

void sobel_filter::thread_p_shl_cast_fu_265_p3() {
    p_shl_cast_fu_265_p3 = esl_concat<11,11>(tmp_14_fu_261_p1.read(), ap_const_lv11_0);
}

void sobel_filter::thread_p_shl_i_cast_fu_431_p1() {
    p_shl_i_cast_fu_431_p1 = esl_zext<16,15>(p_shl_i_fu_423_p3.read());
}

void sobel_filter::thread_p_shl_i_fu_423_p3() {
    p_shl_i_fu_423_p3 = esl_concat<8,7>(p_Val2_3_fu_375_p4.read(), ap_const_lv7_0);
}

void sobel_filter::thread_r_V_fu_371_p1() {
    r_V_fu_371_p1 = inter_pix_V_q0.read().range(8-1, 0);
}

void sobel_filter::thread_row_1_fu_208_p2() {
    row_1_fu_208_p2 = (!row_reg_164.read().is_01() || !ap_const_lv31_1.is_01())? sc_lv<31>(): (sc_biguint<31>(row_reg_164.read()) + sc_biguint<31>(ap_const_lv31_1));
}

void sobel_filter::thread_row_cast_fu_199_p1() {
    row_cast_fu_199_p1 = esl_zext<32,31>(row_reg_164.read());
}

void sobel_filter::thread_tmp1_fu_455_p2() {
    tmp1_fu_455_p2 = (!tmp2_cast_fu_451_p1.read().is_01() || !p_shl_i_cast_fu_431_p1.read().is_01())? sc_lv<16>(): (sc_biguint<16>(tmp2_cast_fu_451_p1.read()) + sc_biguint<16>(p_shl_i_cast_fu_431_p1.read()));
}

void sobel_filter::thread_tmp2_cast_fu_451_p1() {
    tmp2_cast_fu_451_p1 = esl_zext<16,15>(tmp2_fu_445_p2.read());
}

void sobel_filter::thread_tmp2_fu_445_p2() {
    tmp2_fu_445_p2 = (!p_shl2_i_cast_fu_415_p1.read().is_01() || !p_shl1_i_cast_fu_403_p1.read().is_01())? sc_lv<15>(): (sc_biguint<15>(p_shl2_i_cast_fu_415_p1.read()) + sc_biguint<15>(p_shl1_i_cast_fu_403_p1.read()));
}

void sobel_filter::thread_tmp3_cast_fu_477_p1() {
    tmp3_cast_fu_477_p1 = esl_zext<16,13>(tmp3_fu_471_p2.read());
}

void sobel_filter::thread_tmp3_fu_471_p2() {
    tmp3_fu_471_p2 = (!tmp4_cast_fu_467_p1.read().is_01() || !tmp_26_i_fu_439_p2.read().is_01())? sc_lv<13>(): (sc_biguint<13>(tmp4_cast_fu_467_p1.read()) + sc_biguint<13>(tmp_26_i_fu_439_p2.read()));
}

void sobel_filter::thread_tmp4_cast_fu_467_p1() {
    tmp4_cast_fu_467_p1 = esl_zext<13,9>(tmp4_fu_461_p2.read());
}

void sobel_filter::thread_tmp4_fu_461_p2() {
    tmp4_fu_461_p2 = (!ap_const_lv9_80.is_01() || !tmp_23_i_cast5_fu_419_p1.read().is_01())? sc_lv<9>(): (sc_biguint<9>(ap_const_lv9_80) + sc_biguint<9>(tmp_23_i_cast5_fu_419_p1.read()));
}

void sobel_filter::thread_tmp_11_fu_311_p2() {
    tmp_11_fu_311_p2 = (tmp_9_fu_306_p2.read() & tmp_3_reg_533.read());
}

void sobel_filter::thread_tmp_12_fu_366_p1() {
    tmp_12_fu_366_p1 = esl_zext<64,31>(ap_reg_ppstg_ColIndex_assign_reg_175_pp0_it2.read());
}

void sobel_filter::thread_tmp_13_fu_243_p2() {
    tmp_13_fu_243_p2 = (!p_shl2_cast_fu_223_p3.read().is_01() || !p_shl3_cast_fu_235_p3.read().is_01())? sc_lv<22>(): (sc_biguint<22>(p_shl2_cast_fu_223_p3.read()) - sc_biguint<22>(p_shl3_cast_fu_235_p3.read()));
}

void sobel_filter::thread_tmp_14_fu_261_p1() {
    tmp_14_fu_261_p1 = tmp_6_fu_255_p2.read().range(11-1, 0);
}

void sobel_filter::thread_tmp_15_fu_330_p2() {
    tmp_15_fu_330_p2 = (!ColIndex_assign_phi_fu_179_p4.read().is_01() || !ap_const_lv31_0.is_01())? sc_lv<1>(): sc_lv<1>(ColIndex_assign_phi_fu_179_p4.read() != ap_const_lv31_0);
}

void sobel_filter::thread_tmp_16_fu_273_p1() {
    tmp_16_fu_273_p1 = tmp_6_fu_255_p2.read().range(15-1, 0);
}

void sobel_filter::thread_tmp_17_fu_285_p2() {
    tmp_17_fu_285_p2 = (!p_shl_cast_fu_265_p3.read().is_01() || !p_shl1_cast_fu_277_p3.read().is_01())? sc_lv<22>(): (sc_biguint<22>(p_shl_cast_fu_265_p3.read()) - sc_biguint<22>(p_shl1_cast_fu_277_p3.read()));
}

void sobel_filter::thread_tmp_18_fu_316_p1() {
    tmp_18_fu_316_p1 = ColIndex_assign_phi_fu_179_p4.read().range(22-1, 0);
}

void sobel_filter::thread_tmp_19_fu_320_p2() {
    tmp_19_fu_320_p2 = (!tmp_18_fu_316_p1.read().is_01() || !tmp_13_reg_538.read().is_01())? sc_lv<22>(): (sc_biguint<22>(tmp_18_fu_316_p1.read()) + sc_biguint<22>(tmp_13_reg_538.read()));
}

void sobel_filter::thread_tmp_1_fu_193_p2() {
    tmp_1_fu_193_p2 = (!cols.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(cols.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void sobel_filter::thread_tmp_20_cast_fu_325_p1() {
    tmp_20_cast_fu_325_p1 = esl_sext<64,22>(tmp_19_fu_320_p2.read());
}

void sobel_filter::thread_tmp_20_fu_385_p4() {
    tmp_20_fu_385_p4 = inter_pix_V_q0.read().range(23, 16);
}

void sobel_filter::thread_tmp_21_fu_341_p1() {
    tmp_21_fu_341_p1 = ColIndex_assign_phi_fu_179_p4.read().range(22-1, 0);
}

void sobel_filter::thread_tmp_22_fu_345_p2() {
    tmp_22_fu_345_p2 = (!ap_const_lv22_3FFFFF.is_01() || !tmp_21_fu_341_p1.read().is_01())? sc_lv<22>(): (sc_bigint<22>(ap_const_lv22_3FFFFF) + sc_biguint<22>(tmp_21_fu_341_p1.read()));
}

void sobel_filter::thread_tmp_23_fu_351_p2() {
    tmp_23_fu_351_p2 = (!tmp_17_reg_548.read().is_01() || !tmp_22_fu_345_p2.read().is_01())? sc_lv<22>(): (sc_biguint<22>(tmp_17_reg_548.read()) + sc_biguint<22>(tmp_22_fu_345_p2.read()));
}

void sobel_filter::thread_tmp_23_i_cast5_fu_419_p1() {
    tmp_23_i_cast5_fu_419_p1 = esl_zext<9,8>(p_Val2_3_fu_375_p4.read());
}

void sobel_filter::thread_tmp_24_cast_fu_356_p1() {
    tmp_24_cast_fu_356_p1 = esl_sext<64,22>(tmp_23_fu_351_p2.read());
}

void sobel_filter::thread_tmp_26_i_fu_439_p1() {
    tmp_26_i_fu_439_p1 =  (sc_lv<8>) (tmp_26_i_fu_439_p10.read());
}

void sobel_filter::thread_tmp_26_i_fu_439_p10() {
    tmp_26_i_fu_439_p10 = esl_zext<13,8>(r_V_fu_371_p1.read());
}

void sobel_filter::thread_tmp_26_i_fu_439_p2() {
    tmp_26_i_fu_439_p2 = (!ap_const_lv13_19.is_01() || !tmp_26_i_fu_439_p1.read().is_01())? sc_lv<13>(): sc_biguint<13>(ap_const_lv13_19) * sc_biguint<8>(tmp_26_i_fu_439_p1.read());
}

void sobel_filter::thread_tmp_29_i_fu_481_p2() {
    tmp_29_i_fu_481_p2 = (!tmp3_cast_fu_477_p1.read().is_01() || !tmp1_fu_455_p2.read().is_01())? sc_lv<16>(): (sc_biguint<16>(tmp3_cast_fu_477_p1.read()) + sc_biguint<16>(tmp1_fu_455_p2.read()));
}

void sobel_filter::thread_tmp_2_fu_203_p2() {
    tmp_2_fu_203_p2 = (!row_cast_fu_199_p1.read().is_01() || !tmp_reg_514.read().is_01())? sc_lv<1>(): (sc_bigint<32>(row_cast_fu_199_p1.read()) < sc_bigint<32>(tmp_reg_514.read()));
}

void sobel_filter::thread_tmp_31_i_fu_487_p4() {
    tmp_31_i_fu_487_p4 = tmp_29_i_fu_481_p2.read().range(15, 8);
}

void sobel_filter::thread_tmp_3_fu_214_p2() {
    tmp_3_fu_214_p2 = (!row_cast_fu_199_p1.read().is_01() || !rows.read().is_01())? sc_lv<1>(): (sc_bigint<32>(row_cast_fu_199_p1.read()) < sc_bigint<32>(rows.read()));
}

void sobel_filter::thread_tmp_4_fu_219_p1() {
    tmp_4_fu_219_p1 = row_reg_164.read().range(11-1, 0);
}

void sobel_filter::thread_tmp_5_fu_249_p2() {
    tmp_5_fu_249_p2 = (!row_reg_164.read().is_01() || !ap_const_lv31_0.is_01())? sc_lv<1>(): sc_lv<1>(row_reg_164.read() != ap_const_lv31_0);
}

void sobel_filter::thread_tmp_6_fu_255_p2() {
    tmp_6_fu_255_p2 = (!ap_const_lv32_FFFFFFFF.is_01() || !row_cast_fu_199_p1.read().is_01())? sc_lv<32>(): (sc_bigint<32>(ap_const_lv32_FFFFFFFF) + sc_biguint<32>(row_cast_fu_199_p1.read()));
}

void sobel_filter::thread_tmp_7_fu_231_p1() {
    tmp_7_fu_231_p1 = row_reg_164.read().range(15-1, 0);
}

void sobel_filter::thread_tmp_8_fu_295_p2() {
    tmp_8_fu_295_p2 = (!ColIndex_assign_cast_fu_291_p1.read().is_01() || !tmp_1_reg_519.read().is_01())? sc_lv<1>(): (sc_bigint<32>(ColIndex_assign_cast_fu_291_p1.read()) < sc_bigint<32>(tmp_1_reg_519.read()));
}

void sobel_filter::thread_tmp_9_fu_306_p2() {
    tmp_9_fu_306_p2 = (!ColIndex_assign_cast_fu_291_p1.read().is_01() || !cols.read().is_01())? sc_lv<1>(): (sc_bigint<32>(ColIndex_assign_cast_fu_291_p1.read()) < sc_bigint<32>(cols.read()));
}

void sobel_filter::thread_tmp_fu_187_p2() {
    tmp_fu_187_p2 = (!rows.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(rows.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void sobel_filter::thread_tmp_s_fu_361_p1() {
    tmp_s_fu_361_p1 = esl_zext<64,31>(ap_reg_ppstg_ColIndex_assign_reg_175_pp0_it1.read());
}

void sobel_filter::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            ap_NS_fsm = ap_ST_st2_fsm_1;
            break;
        case 2 : 
            if (esl_seteq<1,1,1>(tmp_2_fu_203_p2.read(), ap_const_lv1_0)) {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            } else {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            }
            break;
        case 4 : 
            if ((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it3.read()) && !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read())) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_8_fu_295_p2.read()) && !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_8_fu_295_p2.read()) && !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()))) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            }
            break;
        default : 
            ap_NS_fsm = "XXX";
            break;
    }
}

void sobel_filter::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"inter_pix_V_address0\" :  \"" << inter_pix_V_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"inter_pix_V_ce0\" :  \"" << inter_pix_V_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"inter_pix_V_q0\" :  \"" << inter_pix_V_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_pix_V_address0\" :  \"" << out_pix_V_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_pix_V_ce0\" :  \"" << out_pix_V_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_pix_V_we0\" :  \"" << out_pix_V_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_pix_V_d0\" :  \"" << out_pix_V_d0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"rows\" :  \"" << rows.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"cols\" :  \"" << cols.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

