# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7a35tcpg236-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir e:/Basys3/Projects/1_Logic_Design/2_SN_Design/Digilent_Abacus_Design/Src/prj/Digilent_Abacus_Design.cache/wt [current_project]
set_property parent.project_path e:/Basys3/Projects/1_Logic_Design/2_SN_Design/Digilent_Abacus_Design/Src/prj/Digilent_Abacus_Design.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  e:/Basys3/Projects/1_Logic_Design/2_SN_Design/Digilent_Abacus_Design/Src/prj/Digilent_Abacus_Design.srcs/sources_1/imports/HDL_source/Adder_Subtractor.v
  e:/Basys3/Projects/1_Logic_Design/2_SN_Design/Digilent_Abacus_Design/Src/prj/Digilent_Abacus_Design.srcs/sources_1/imports/HDL_source/Binary_to_BCD_B1_bcdout1.v
  e:/Basys3/Projects/1_Logic_Design/2_SN_Design/Digilent_Abacus_Design/Src/prj/Digilent_Abacus_Design.srcs/sources_1/imports/HDL_source/Binary_to_BCD_B2_bcdout2.v
  e:/Basys3/Projects/1_Logic_Design/2_SN_Design/Digilent_Abacus_Design/Src/prj/Digilent_Abacus_Design.srcs/sources_1/imports/HDL_source/Binary_to_BCD_B_bcdout.v
  e:/Basys3/Projects/1_Logic_Design/2_SN_Design/Digilent_Abacus_Design/Src/prj/Digilent_Abacus_Design.srcs/sources_1/imports/HDL_source/Display_QU.v
  e:/Basys3/Projects/1_Logic_Design/2_SN_Design/Digilent_Abacus_Design/Src/prj/Digilent_Abacus_Design.srcs/sources_1/imports/HDL_source/Display_REM.v
  e:/Basys3/Projects/1_Logic_Design/2_SN_Design/Digilent_Abacus_Design/Src/prj/Digilent_Abacus_Design.srcs/sources_1/imports/HDL_source/Divider.v
  e:/Basys3/Projects/1_Logic_Design/2_SN_Design/Digilent_Abacus_Design/Src/prj/Digilent_Abacus_Design.srcs/sources_1/imports/HDL_source/multi_4_4_pp0.v
  e:/Basys3/Projects/1_Logic_Design/2_SN_Design/Digilent_Abacus_Design/Src/prj/Digilent_Abacus_Design.srcs/sources_1/imports/HDL_source/multi_4_4_pp1.v
  e:/Basys3/Projects/1_Logic_Design/2_SN_Design/Digilent_Abacus_Design/Src/prj/Digilent_Abacus_Design.srcs/sources_1/imports/HDL_source/multi_4_4_pp2.v
  e:/Basys3/Projects/1_Logic_Design/2_SN_Design/Digilent_Abacus_Design/Src/prj/Digilent_Abacus_Design.srcs/sources_1/imports/HDL_source/multi_4_4_pp3.v
  e:/Basys3/Projects/1_Logic_Design/2_SN_Design/Digilent_Abacus_Design/Src/prj/Digilent_Abacus_Design.srcs/sources_1/imports/HDL_source/Segment_Scroll.v
  e:/Basys3/Projects/1_Logic_Design/2_SN_Design/Digilent_Abacus_Design/Src/prj/Digilent_Abacus_Design.srcs/sources_1/imports/HDL_source/Seg_7_Display.v
  e:/Basys3/Projects/1_Logic_Design/2_SN_Design/Digilent_Abacus_Design/Src/prj/Digilent_Abacus_Design.srcs/sources_1/imports/HDL_source/Basys3_Abacus_Top.v
}
read_xdc e:/Basys3/Projects/1_Logic_Design/2_SN_Design/Digilent_Abacus_Design/Src/prj/Digilent_Abacus_Design.srcs/constrs_1/imports/Constraint/Basys3_Master.xdc
set_property used_in_implementation false [get_files e:/Basys3/Projects/1_Logic_Design/2_SN_Design/Digilent_Abacus_Design/Src/prj/Digilent_Abacus_Design.srcs/constrs_1/imports/Constraint/Basys3_Master.xdc]

catch { write_hwdef -file Basys3_Abacus_Top.hwdef }
synth_design -top Basys3_Abacus_Top -part xc7a35tcpg236-1
write_checkpoint -noxdef Basys3_Abacus_Top.dcp
catch { report_utilization -file Basys3_Abacus_Top_utilization_synth.rpt -pb Basys3_Abacus_Top_utilization_synth.pb }
