// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#ifndef _sobel_filter_HH_
#define _sobel_filter_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "sobel_filter_buff_A_M_0.h"
#include "sobel_filter_buff_A_M_1.h"

namespace ap_rtl {

struct sobel_filter : public sc_module {
    // Port declarations 11
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_out< sc_lv<21> > inter_pix_V_address0;
    sc_out< sc_logic > inter_pix_V_ce0;
    sc_in< sc_lv<24> > inter_pix_V_q0;
    sc_out< sc_lv<21> > out_pix_V_address0;
    sc_out< sc_logic > out_pix_V_ce0;
    sc_out< sc_logic > out_pix_V_we0;
    sc_out< sc_lv<24> > out_pix_V_d0;
    sc_in< sc_lv<32> > rows;
    sc_in< sc_lv<32> > cols;


    // Module declarations
    sobel_filter(sc_module_name name);
    SC_HAS_PROCESS(sobel_filter);

    ~sobel_filter();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    sobel_filter_buff_A_M_0* buff_A_M_0_U;
    sobel_filter_buff_A_M_1* buff_A_M_1_U;
    sc_signal< sc_lv<31> > ColIndex_assign_reg_175;
    sc_signal< sc_lv<31> > ap_reg_ppstg_ColIndex_assign_reg_175_pp0_it1;
    sc_signal< sc_lv<3> > ap_CS_fsm;
    sc_signal< sc_logic > ap_sig_cseq_ST_pp0_stg0_fsm_2;
    sc_signal< bool > ap_sig_bdd_34;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it0;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it1;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it2;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it3;
    sc_signal< sc_lv<31> > ap_reg_ppstg_ColIndex_assign_reg_175_pp0_it2;
    sc_signal< sc_logic > ap_sig_cseq_ST_st1_fsm_0;
    sc_signal< bool > ap_sig_bdd_53;
    sc_signal< sc_lv<32> > tmp_fu_187_p2;
    sc_signal< sc_lv<32> > tmp_reg_514;
    sc_signal< sc_lv<32> > tmp_1_fu_193_p2;
    sc_signal< sc_lv<32> > tmp_1_reg_519;
    sc_signal< sc_lv<1> > tmp_2_fu_203_p2;
    sc_signal< sc_logic > ap_sig_cseq_ST_st2_fsm_1;
    sc_signal< bool > ap_sig_bdd_68;
    sc_signal< sc_lv<31> > row_1_fu_208_p2;
    sc_signal< sc_lv<31> > row_1_reg_528;
    sc_signal< sc_lv<1> > tmp_3_fu_214_p2;
    sc_signal< sc_lv<1> > tmp_3_reg_533;
    sc_signal< sc_lv<22> > tmp_13_fu_243_p2;
    sc_signal< sc_lv<22> > tmp_13_reg_538;
    sc_signal< sc_lv<1> > tmp_5_fu_249_p2;
    sc_signal< sc_lv<1> > tmp_5_reg_543;
    sc_signal< sc_lv<22> > tmp_17_fu_285_p2;
    sc_signal< sc_lv<22> > tmp_17_reg_548;
    sc_signal< sc_lv<1> > tmp_8_fu_295_p2;
    sc_signal< sc_lv<1> > tmp_8_reg_553;
    sc_signal< sc_lv<31> > col_fu_300_p2;
    sc_signal< sc_lv<31> > col_reg_557;
    sc_signal< sc_lv<1> > tmp_9_fu_306_p2;
    sc_signal< sc_lv<1> > tmp_9_reg_562;
    sc_signal< sc_lv<1> > ap_reg_ppstg_tmp_9_reg_562_pp0_it1;
    sc_signal< sc_lv<1> > ap_reg_ppstg_tmp_9_reg_562_pp0_it2;
    sc_signal< sc_lv<1> > tmp_11_fu_311_p2;
    sc_signal< sc_lv<1> > tmp_11_reg_566;
    sc_signal< sc_lv<1> > ap_reg_ppstg_tmp_11_reg_566_pp0_it1;
    sc_signal< sc_lv<1> > ap_reg_ppstg_tmp_11_reg_566_pp0_it2;
    sc_signal< sc_lv<1> > or_cond_fu_336_p2;
    sc_signal< sc_lv<64> > tmp_s_fu_361_p1;
    sc_signal< sc_lv<64> > tmp_s_reg_584;
    sc_signal< sc_lv<11> > buff_A_M_0_address0;
    sc_signal< sc_logic > buff_A_M_0_ce0;
    sc_signal< sc_lv<8> > buff_A_M_0_q0;
    sc_signal< sc_lv<11> > buff_A_M_0_address1;
    sc_signal< sc_logic > buff_A_M_0_ce1;
    sc_signal< sc_logic > buff_A_M_0_we1;
    sc_signal< sc_lv<8> > buff_A_M_0_d1;
    sc_signal< sc_lv<11> > buff_A_M_1_address0;
    sc_signal< sc_logic > buff_A_M_1_ce0;
    sc_signal< sc_logic > buff_A_M_1_we0;
    sc_signal< sc_lv<8> > buff_A_M_1_d0;
    sc_signal< sc_lv<31> > row_reg_164;
    sc_signal< sc_lv<31> > ColIndex_assign_phi_fu_179_p4;
    sc_signal< sc_lv<64> > tmp_20_cast_fu_325_p1;
    sc_signal< sc_lv<64> > tmp_24_cast_fu_356_p1;
    sc_signal< sc_lv<64> > tmp_12_fu_366_p1;
    sc_signal< sc_lv<32> > row_cast_fu_199_p1;
    sc_signal< sc_lv<11> > tmp_4_fu_219_p1;
    sc_signal< sc_lv<15> > tmp_7_fu_231_p1;
    sc_signal< sc_lv<22> > p_shl2_cast_fu_223_p3;
    sc_signal< sc_lv<22> > p_shl3_cast_fu_235_p3;
    sc_signal< sc_lv<32> > tmp_6_fu_255_p2;
    sc_signal< sc_lv<11> > tmp_14_fu_261_p1;
    sc_signal< sc_lv<15> > tmp_16_fu_273_p1;
    sc_signal< sc_lv<22> > p_shl_cast_fu_265_p3;
    sc_signal< sc_lv<22> > p_shl1_cast_fu_277_p3;
    sc_signal< sc_lv<32> > ColIndex_assign_cast_fu_291_p1;
    sc_signal< sc_lv<22> > tmp_18_fu_316_p1;
    sc_signal< sc_lv<22> > tmp_19_fu_320_p2;
    sc_signal< sc_lv<1> > tmp_15_fu_330_p2;
    sc_signal< sc_lv<22> > tmp_21_fu_341_p1;
    sc_signal< sc_lv<22> > tmp_22_fu_345_p2;
    sc_signal< sc_lv<22> > tmp_23_fu_351_p2;
    sc_signal< sc_lv<8> > tmp_20_fu_385_p4;
    sc_signal< sc_lv<14> > p_shl1_i_fu_395_p3;
    sc_signal< sc_lv<9> > p_shl2_i_fu_407_p3;
    sc_signal< sc_lv<8> > p_Val2_3_fu_375_p4;
    sc_signal< sc_lv<15> > p_shl_i_fu_423_p3;
    sc_signal< sc_lv<8> > r_V_fu_371_p1;
    sc_signal< sc_lv<8> > tmp_26_i_fu_439_p1;
    sc_signal< sc_lv<15> > p_shl2_i_cast_fu_415_p1;
    sc_signal< sc_lv<15> > p_shl1_i_cast_fu_403_p1;
    sc_signal< sc_lv<15> > tmp2_fu_445_p2;
    sc_signal< sc_lv<16> > tmp2_cast_fu_451_p1;
    sc_signal< sc_lv<16> > p_shl_i_cast_fu_431_p1;
    sc_signal< sc_lv<9> > tmp_23_i_cast5_fu_419_p1;
    sc_signal< sc_lv<9> > tmp4_fu_461_p2;
    sc_signal< sc_lv<13> > tmp4_cast_fu_467_p1;
    sc_signal< sc_lv<13> > tmp_26_i_fu_439_p2;
    sc_signal< sc_lv<13> > tmp3_fu_471_p2;
    sc_signal< sc_lv<16> > tmp3_cast_fu_477_p1;
    sc_signal< sc_lv<16> > tmp1_fu_455_p2;
    sc_signal< sc_lv<16> > tmp_29_i_fu_481_p2;
    sc_signal< sc_lv<8> > tmp_31_i_fu_487_p4;
    sc_signal< sc_lv<3> > ap_NS_fsm;
    sc_signal< sc_lv<13> > tmp_26_i_fu_439_p10;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<3> ap_ST_st1_fsm_0;
    static const sc_lv<3> ap_ST_st2_fsm_1;
    static const sc_lv<3> ap_ST_pp0_stg0_fsm_2;
    static const bool ap_true;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<31> ap_const_lv31_0;
    static const sc_lv<24> ap_const_lv24_0;
    static const sc_lv<31> ap_const_lv31_1;
    static const sc_lv<11> ap_const_lv11_0;
    static const sc_lv<7> ap_const_lv7_0;
    static const sc_lv<32> ap_const_lv32_FFFFFFFF;
    static const sc_lv<22> ap_const_lv22_3FFFFF;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_F;
    static const sc_lv<32> ap_const_lv32_10;
    static const sc_lv<32> ap_const_lv32_17;
    static const sc_lv<6> ap_const_lv6_0;
    static const sc_lv<13> ap_const_lv13_19;
    static const sc_lv<9> ap_const_lv9_80;
    static const sc_lv<8> ap_const_lv8_10;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ColIndex_assign_cast_fu_291_p1();
    void thread_ColIndex_assign_phi_fu_179_p4();
    void thread_ap_sig_bdd_34();
    void thread_ap_sig_bdd_53();
    void thread_ap_sig_bdd_68();
    void thread_ap_sig_cseq_ST_pp0_stg0_fsm_2();
    void thread_ap_sig_cseq_ST_st1_fsm_0();
    void thread_ap_sig_cseq_ST_st2_fsm_1();
    void thread_buff_A_M_0_address0();
    void thread_buff_A_M_0_address1();
    void thread_buff_A_M_0_ce0();
    void thread_buff_A_M_0_ce1();
    void thread_buff_A_M_0_d1();
    void thread_buff_A_M_0_we1();
    void thread_buff_A_M_1_address0();
    void thread_buff_A_M_1_ce0();
    void thread_buff_A_M_1_d0();
    void thread_buff_A_M_1_we0();
    void thread_col_fu_300_p2();
    void thread_inter_pix_V_address0();
    void thread_inter_pix_V_ce0();
    void thread_or_cond_fu_336_p2();
    void thread_out_pix_V_address0();
    void thread_out_pix_V_ce0();
    void thread_out_pix_V_d0();
    void thread_out_pix_V_we0();
    void thread_p_Val2_3_fu_375_p4();
    void thread_p_shl1_cast_fu_277_p3();
    void thread_p_shl1_i_cast_fu_403_p1();
    void thread_p_shl1_i_fu_395_p3();
    void thread_p_shl2_cast_fu_223_p3();
    void thread_p_shl2_i_cast_fu_415_p1();
    void thread_p_shl2_i_fu_407_p3();
    void thread_p_shl3_cast_fu_235_p3();
    void thread_p_shl_cast_fu_265_p3();
    void thread_p_shl_i_cast_fu_431_p1();
    void thread_p_shl_i_fu_423_p3();
    void thread_r_V_fu_371_p1();
    void thread_row_1_fu_208_p2();
    void thread_row_cast_fu_199_p1();
    void thread_tmp1_fu_455_p2();
    void thread_tmp2_cast_fu_451_p1();
    void thread_tmp2_fu_445_p2();
    void thread_tmp3_cast_fu_477_p1();
    void thread_tmp3_fu_471_p2();
    void thread_tmp4_cast_fu_467_p1();
    void thread_tmp4_fu_461_p2();
    void thread_tmp_11_fu_311_p2();
    void thread_tmp_12_fu_366_p1();
    void thread_tmp_13_fu_243_p2();
    void thread_tmp_14_fu_261_p1();
    void thread_tmp_15_fu_330_p2();
    void thread_tmp_16_fu_273_p1();
    void thread_tmp_17_fu_285_p2();
    void thread_tmp_18_fu_316_p1();
    void thread_tmp_19_fu_320_p2();
    void thread_tmp_1_fu_193_p2();
    void thread_tmp_20_cast_fu_325_p1();
    void thread_tmp_20_fu_385_p4();
    void thread_tmp_21_fu_341_p1();
    void thread_tmp_22_fu_345_p2();
    void thread_tmp_23_fu_351_p2();
    void thread_tmp_23_i_cast5_fu_419_p1();
    void thread_tmp_24_cast_fu_356_p1();
    void thread_tmp_26_i_fu_439_p1();
    void thread_tmp_26_i_fu_439_p10();
    void thread_tmp_26_i_fu_439_p2();
    void thread_tmp_29_i_fu_481_p2();
    void thread_tmp_2_fu_203_p2();
    void thread_tmp_31_i_fu_487_p4();
    void thread_tmp_3_fu_214_p2();
    void thread_tmp_4_fu_219_p1();
    void thread_tmp_5_fu_249_p2();
    void thread_tmp_6_fu_255_p2();
    void thread_tmp_7_fu_231_p1();
    void thread_tmp_8_fu_295_p2();
    void thread_tmp_9_fu_306_p2();
    void thread_tmp_fu_187_p2();
    void thread_tmp_s_fu_361_p1();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
